### ISSUE TITLE
Eclipse ValidationException during application start

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/jmix-entity-soft-reference#1]
When creating a new entity attribute using entity soft reference from `Document` the following exception happens at application start:

```
11:00:59: Executing task 'bootRun'...

> Task :bootBuildInfo

> Task :compileJava
Enhancing entities in root project 'jesrexample' for source set 'main'
Project entities:
    JPA: [de.diedavids.jmix.jesrexample.entity.User, de.diedavids.jmix.jesrexample.entity.Document, de.diedavids.jmix.jesrexample.entity.Customer, de.diedavids.jmix.jesrexample.entity.Order];
    DTO: [];
Project converters: [].
Running EclipseLink enhancer in root project 'jesrexample' for source set 'main'
Exception in thread "main" Local Exception Stack: 
Exception [EclipseLink-40007] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.StaticWeaveException
Exception Description: An exception was thrown while weaving: [Ljava.lang.String;@4b86805d
Internal Exception: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [main] failed.
Internal Exception: Exception [EclipseLink-7353] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The mapping attribute [refersTo] from the class [de.diedavids.jmix.jesrexample.entity.Document] is not a valid mapping type for a convert specification.
	at org.eclipse.persistence.exceptions.StaticWeaveException.exceptionPerformWeaving(StaticWeaveException.java:140)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeave.main(StaticWeave.java:88)
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [main] failed.
Internal Exception: Exception [EclipseLink-7353] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The mapping attribute [refersTo] from the class [de.diedavids.jmix.jesrexample.entity.Document] is not a valid mapping type for a convert specification.
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2112)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2088)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeaveClassTransformer.buildClassTransformers(StaticWeaveClassTransformer.java:128)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeaveClassTransformer.<init>(StaticWeaveClassTransformer.java:78)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeaveProcessor.process(StaticWeaveProcessor.java:252)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeaveProcessor.performWeaving(StaticWeaveProcessor.java:174)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeave.start(StaticWeave.java:117)
	at org.eclipse.persistence.tools.weaving.jpa.StaticWeave.main(StaticWeave.java:86)
Caused by: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [main] failed.
Internal Exception: Exception [EclipseLink-7353] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The mapping attribute [refersTo] from the class [de.diedavids.jmix.jesrexample.entity.Document] is not a valid mapping type for a convert specification.
	at org.eclipse.persistence.exceptions.EntityManagerSetupException.predeployFailed(EntityManagerSetupException.java:233)
	... 8 more
Caused by: Exception [EclipseLink-7353] (Eclipse Persistence Services - 2.7.9.5-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The mapping attribute [refersTo] from the class [de.diedavids.jmix.jesrexample.entity.Document] is not a valid mapping type for a convert specification.
	at org.eclipse.persistence.exceptions.ValidationException.invalidMappingForConvert(ValidationException.java:2290)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.addConvert(MappingAccessor.java:257)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.addConvertMetadata(MappingAccessor.java:270)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.<init>(MappingAccessor.java:239)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.RelationshipAccessor.<init>(RelationshipAccessor.java:147)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor.<init>(ObjectAccessor.java:143)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.VariableOneToOneAccessor.<init>(VariableOneToOneAccessor.java:99)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.buildAccessor(ClassAccessor.java:617)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.addAccessorFields(ClassAccessor.java:438)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.addAccessors(ClassAccessor.java:410)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.preProcess(ClassAccessor.java:1225)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.MappedSuperclassAccessor.preProcess(MappedSuperclassAccessor.java:751)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.preProcess(EntityAccessor.java:621)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage1(MetadataProject.java:1826)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:579)
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:629)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2009)
	... 6 more

> Task :compileJava FAILED
```

## Example

See example project: https://github.com/mariodavid/jmix-entity-soft-reference-example

## Classes

[Document](https://github.com/mariodavid/jmix-entity-soft-reference-example/blob/main/src/main/java/de/diedavids/jmix/jesrexample/entity/Document.java) Entity:
```
package de.diedavids.jmix.jesrexample.entity;

import de.diedavids.jmix.jesr.entity.EntitySoftReferenceConverter;
import io.jmix.core.FileRef;
import io.jmix.core.entity.annotation.JmixGeneratedValue;
import io.jmix.core.metamodel.annotation.InstanceName;
import io.jmix.core.metamodel.annotation.JmixEntity;
import io.jmix.core.metamodel.annotation.PropertyDatatype;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.UUID;

@JmixEntity
@Table(name = "DOCUMENT")
@Entity
public class Document {
    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    private UUID id;

    @InstanceName
    @Column(name = "NAME")
    private String name;

    @Column(name = "FILE_", length = 1024)
    private FileRef file;

    @PropertyDatatype("EntitySoftReference")
    @Column(name = "REFERS_TO")
    @Convert(converter = EntitySoftReferenceConverter.class)
    private io.jmix.core.Entity refersTo;

    public io.jmix.core.Entity getRefersTo() {
        return refersTo;
    }

    public void setRefersTo(io.jmix.core.Entity refersTo) {
        this.refersTo = refersTo;
    }
  // ...
}
```

[EntitySoftReferenceConverter](https://github.com/mariodavid/jmix-entity-soft-reference/blob/main/jmix-entity-soft-reference/src/main/java/de/diedavids/jmix/jesr/entity/EntitySoftReferenceConverter.java):
```
@Converter(autoApply = true)
public class EntitySoftReferenceConverter implements AttributeConverter<Entity, String> {

    private final EntitySoftReference entitySoftReference;

    public EntitySoftReferenceConverter(EntitySoftReference entitySoftReference) {
        this.entitySoftReference = entitySoftReference;
    }

    @Override
    public String convertToDatabaseColumn(Entity entity) {
        return entitySoftReference.toEntityReference(entity);
    }

    @Override
    public Entity convertToEntityAttribute(String value) {
        return entitySoftReference.toEntity(value);
    }

}
```

[EntitySoftReferenceDatatype](https://github.com/mariodavid/jmix-entity-soft-reference/blob/main/jmix-entity-soft-reference/src/main/java/de/diedavids/jmix/jesr/entity/EntitySoftReferenceDatatype.java):
```

@DatatypeDef(
        id = "EntitySoftReference",
        javaClass = Entity.class
)
@Ddl("varchar(255)")
public class EntitySoftReferenceDatatype implements Datatype<Entity> {


    /**
     * workaround to inject application context to retrieve IdSerialization
     * until direct injection of IdSerialization is supported
     *
     * see: https://github.com/Haulmont/jmix-core/issues/272
     */
    private final ApplicationContext applicationContext;

    public EntitySoftReferenceDatatype(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
    }

    @Override
    public Class getJavaClass() {
        return Entity.class;
    }

    @Nonnull
    @Override
    public String format(@Nullable Object value) {
        return entitySoftReference().toEntityReference(value);
    }

    @Nonnull
    @Override
    public String format(@Nullable Object value, Locale locale) {
        return format(value);
    }

    @Nullable
    @Override
    public Entity parse(@Nullable String value) {
        return entitySoftReference().toEntity(value);
    }

    @Nullable
    @Override
    public Entity parse(@Nullable String value, Locale locale) {
        return parse(value);
    }

    private EntitySoftReference entitySoftReference() {
        return applicationContext.getBean(EntitySoftReference.class);
    }
}
```

**Comment by mariodavid** [comment]
solved by switching to Object (with additional interface definition) instead of Entity.
